### ISSUE TITLE
Implementar tela de detalhes do periódico

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/journals-opac#10]
Esta atividade é dependente dos tickets [ #7, #8 ]

Nesta primeira versão, os objetos de domínio devem utilizar as fixtures como fonte de dados ao invés de comunicar com o MongoDB.

Ver o [mockup](https://github.com/scieloorg/journals-opac/blob/master/public-mockups/journalHome.html)

**Comment by fabiobatalha** [comment]
atividade finalizada.
