### ISSUE TITLE
Desenvolver área administrativa do OPAC

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/journals-opac#11]
Baseado no [documento de visão](http://docs.scielo.org/projects/journals-opac/en/latest/dev/vision.html#macro-necessidades) desenvolver a área administrativa.

**Comment by gustavofonseca** [comment]
É importante dizer que este ticket tornou-se invalido pois foi tomada a decisão de customizar a app _django.contrib.admin_ para atender os requisitos de montagem do catálogo.
