### ISSUE TITLE
Criar template da grade dos fascículos

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/journals-opac#43]
Criar mockup e template para a página de issues(grid), utilizar os recursos da bootstrap disponíveis, ver: http://twitter.github.com/bootstrap/scaffolding.html#gridSystem

Criar métodos necessários na entidade Issue.

Exemplo de grade no site atual: http://www.scielo.br/scielo.php?script=sci_issues&pid=0100-879X&lng=en&nrm=iso

**Comment by jamilatta** [comment]
Para criação da grade foi utilizado tabela, div(s) e li(s).

```
  <div class="span12">
    <table class="table_issue">
      <thead>
        <tr>
          <th>{% trans 'Year' %}</th>
          <th>{% trans 'Volume' %}</th>
          <th>{% trans 'Numbers' %}</th>
        </tr>
      </thead>
          <tr>
            <th>2013</th>
            <th>45</th>
            <td>
              <div class="table_issue_div">
                <ul class="table_issue_ul">
                  <li class="table_issue_li"><a href="#">1</a></li>
                  <li class="table_issue_li"><a href="#">2</a></li>
                </ul>
              </div>
              </td>
          </tr>
    </table>
  </div>
```

**Comment by gustavofonseca** [comment]
Algum motivo para não ter implementado o mockup? https://github.com/scieloorg/journals-opac/blob/master/public-mockups/allIssues.html

**Comment by jamilatta** [comment]
Não entendi, estamos desenvolvendo um interface baseado no site atual!

**Comment by gustavofonseca** [comment]
O HTML tb não está igual ao do site atual. Enfim, agora temos 3 implementações de grade de fascículos.

**Comment by jamilatta** [comment]
Entendi você esta se referindo ao HTML e não ao design, posso utilizar o que esta na proposta, porém ficariamos no mínino com dois HTMLs, pois o SciELO Manager utiliza este HTML para representar a grade, sei que são aplicações diferente, porém com a mesma apresentação no fascículos.

Verifiquei o HTML proposto.... repare a verbosidade do HTML (`<td>&nbsp;<td>`) para contemplar o espaçamento, no minino desnecessário.

Acredito que o ideal seja mantermos o código proposto, desconsiderando o antigo o que no caso não interessa mais, pois resolvemos utilizar um html mais limpo e aproveitarmos o fato de o SciELO Manager também utiliza, pensando em futuras manutenções.

No futuro se for necessário termos uma grade igual ao proposto utilizamos os recursos da css para replicar esse design com um HTML mais limpo.

**Comment by gustavofonseca** [comment]
A implementação do Manager é bastante diferente pq é arquitetado para
permitir a reordenação e talz, no contrário não há a necessidade dos
elementos <li>.

2013/2/7 Jamil Atta Junior notifications@github.com

**Comment by jamilatta** [comment]
Qual sugestão você teria para não utilizarmos elementos `<li>`

**Comment by gustavofonseca** [comment]
Sendo o grid uma tabela, não poderiam ser elementos <td>?

On Thu, Feb 7, 2013 at 11:53 AM, Jamil Atta Junior <notifications@github.com

**Comment by jamilatta** [comment]
Poderiamos, porém estariamos com o mesmo problema que a proposta tem, elementos vazios.

**Comment by jamilatta** [comment]
Concordamos em utilizar uma determinada versão feita para o SciELO Manager.

Este código é parecido com este: 

```

  <div class="span12">
    <table class="table_issue">
      <thead>
        <tr>
          <th>{% trans 'Year' %}</th>
          <th>{% trans 'Volume' %}</th>
          <th>{% trans 'Numbers' %}</th>
        </tr>
      </thead>
      <tbody>
        {% for year, vols in issues.items %}
          {% for vol, nums in vols.items %}
          <tr>
            <th>{{ year }}</th>
            <th>{{ vol|default:'-' }}</th>
            {% for num in nums %}
              {% if num.suppl_number %}
                <td><a href="#">{% trans 'suppl.' %}</a></td>
              {% elif num.suppl_volume %}
                <td><a href="#">{% trans 'suppl.' %} {{ num.suppl_volume }}</a></td>
              {% elif not num.is_press_release %}
                <td><a href="#">{{ num.number }}</a></td>
              {% endif %}
            {% endfor %}
          </tr>
          {% endfor %}
        {% endfor %}
      <tbody>
    </table>
  </div>
```
