### ISSUE TITLE
O filtro de fascículo não funciona como imaginávamos.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/journals-opac#50]
Naaaaao!!!!!

Fazendo um filtro pelo issue_id=1694 o resultado é id=1432

> mongomodels.Issue().get_issue(journal_id='rsp', issue_id=1694)._data
> {'total_documents': 14, 'ctrl_vocabulary': u'decs', 'number': u'1', 'is_press_release': False, 'editorial_standard': u'vancouv', 'id': 1432, 'publication_start_month': 6, 'suppl_number': None, 'publication_end_month': 6, 'label': u'1 (1)', 'sections': [{u'id': 651}, {u'id': 677}, {u'id': 692}, {u'id': 703}, {u'id': 709}], 'updated': u'2013-01-21T12:22:01.693866', 'acronym': 'rsp', 'suppl_volume': None, 'volume': u'1', '_data': {}, 'is_trashed': False, 'is_marked_up': False, 'created': u'2006-09-01T01:01:01', 'cover': None, 'publication_year': 1967, 'order': 1, 'resource_uri': u'/api/v1/issues/1432/'}

Fazendo um filtro pelo issue_id=1595 o resultado é id=1432

> mongomodels.Issue().get_issue(journal_id='rsp', issue_id=1695)._data
> {'total_documents': 14, 'ctrl_vocabulary': u'decs', 'number': u'1', 'is_press_release': False, 'editorial_standard': u'vancouv', 'id': 1432, 'publication_start_month': 6, 'suppl_number': None, 'publication_end_month': 6, 'label': u'1 (1)', 'sections': [{u'id': 651}, {u'id': 677}, {u'id': 692}, {u'id': 703}, {u'id': 709}], 'updated': u'2013-01-21T12:22:01.693866', 'acronym': 'rsp', 'suppl_volume': None, 'volume': u'1', '_data': {}, 'is_trashed': False, 'is_marked_up': False, 'created': u'2006-09-01T01:01:01', 'cover': None, 'publication_year': 1967, 'order': 1, 'resource_uri': u'/api/v1/issues/1432/'}

O resultado sempre será o primeiro item da lista de issues.

Na verdade o filtro só serve para fazer match de journal, entretanto a estrutura de dados que retorna é sempre completa, com todos os issues. :-1:

**Comment by jamilatta** [comment]
Ver: http://stackoverflow.com/questions/2138454/filtering-embedded-documents-in-mongodb

**Comment by jamilatta** [comment]
Ver: http://stackoverflow.com/questions/2268568/mongodb-query-to-return-only-embedded-document

**Comment by jamilatta** [comment]
Realmente achavamos que o mongodb retornava somente o "embedded document" que especificavamos na pesquisa.

**Comment by jamilatta** [comment]
Verifiquei na documentação do mongodb e existe um operador de projeção que permite que seja retornado um elemento no array.

[$elemMatch](http://docs.mongodb.org/manual/reference/projection/elemMatch/#_S_elemMatch)

No nosso caso seria algo desse tipo para issue: 

```
db.journals.find(
 {'acronym': <ACRONYM_JOURNAL>}, 
 {issues: {$elemMatch: {id: <ID_ISSUE>}}
})
```

e algo desse tipo para section: 

```
db.journals.find(
 {'acronym': <ACRONYM_JOURNAL>}, 
 { sections: {$elemMatch:{id: <ID_SECTION>}}
})
```

**Comment by jamilatta** [comment]
Pessoal, 

mais alguma sugestão... para melhor resolvermos esse bug?

**Comment by gustavofonseca** [comment]
Vc já fez uma prova de conceito utilizando o $elemMatch? Acho que fica mais fácil tomar uma decisão se vc já apresentar alguns resultados.

**Comment by jamilatta** [comment]
Realizei testes utilizando os dados reais cadastrados na minha instância de mongoDB, segue um exemplo do teste que realizei: 

Link para os dados (Journal com acrônimo: 'bwho'): https://gist.github.com/jamilatta/4960022#file-data_simple-json 

Considerando esse journal... para obter um fascículo:

```
db.journals.findOne({'acronym': 'bwho'}, {issues: {$elemMatch: {'id': 1996}}})
```

para obter uma seção utilize: 

```
db.journals.findOne({'acronym': 'bwho'}, {sections: {$elemMatch: {'id': 933}}})
```

Retornos,  repectivamente:

```
{
    "_id" : ObjectId("51100441cdda6f2e349f3902"),
    "issues" : [
        {
            "data" : {
                "is_press_release" : false,
                "ctrl_vocabulary" : "decs",
                "number" : "1",
                "total_documents" : 15,
                "label" : "91 (1)",
                "id" : 1996,
                "publication_start_month" : 1,
                "suppl_number" : null,
                "publication_end_month" : 1,
                "editorial_standard" : "other",
                "sections" : [
                    {
                        "id" : 889
                    },
                    {
                        "id" : 899
                    },
                    {
                        "id" : 903
                    },
                    {
                        "id" : 904
                    },
                    {
                        "id" : 912
                    },
                    {
                        "id" : 918
                    },
                    {
                        "id" : 931
                    },
                    {
                        "id" : 933
                    }
                ],
                "updated" : "2013-01-21T12:22:12.088401",
                "suppl_volume" : null,
                "volume" : "91",
                "is_trashed" : false,
                "is_marked_up" : true,
                "created" : "2013-01-01T01:01:01",
                "cover" : null,
                "publication_year" : 2013,
                "order" : 1,
                "resource_uri" : "/api/v1/issues/1996/"
            },
            "id" : 1996
        }
    ]
}
```

```
{
    "_id" : ObjectId("51100441cdda6f2e349f3902"),
    "sections" : [
        {
            "titles" : [
                {
                    "en" : "Lessons from the Field"
                }
            ],
            "id" : 933,
            "resource_uri" : "/api/v1/sections/933/"
        }
    ]
}
```
