### ISSUE TITLE
Métodos de objeto **Navigation** devem retornar URLs ou levantar exceção.

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/journals-opac#52]
Por tratar-se de um objeto intimamente relacionado a navegação, penso que não há motivo para retornarem algo que não URLs ou levantar exceção.

**Comment by fabiobatalha** [comment]
De acordo.

O Retorno de algo para ser aplicado na interface ficaria a cargo de quem utiliza o objeto **Navigation**

**Comment by fabiobatalha** [comment]
Gustavo, de acordo com o que conversamos, vamos ajustar os retornos dos metodos da classe navigation para uma url ou uma exceção. As views que farão uso da classe navigation e tratarão o retorno para enviar para o template.

Se estiver de acordo, vamos passar essa discussão para um ticket.

**Comment by gustavofonseca** [comment]
ok!
