### ISSUE TITLE
Funcionalidades básicas da interface administrativa para a escolha do conteúdo do catálogo

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/journals-opac#55]
## Descrição

A interface administrativa deve permitir que usuários que operam o backoffice da aplicação OPAC selecionem de maneira interativa o conteúdo do catálogo.

Na implementação **inicial**, os catálogos devem: 
- Refletir uma única coleção em sua totalidade;
- Refletir um subconjunto de periódicos de uma única coleção;
## Estratégia de implementação

Utilizando do modelo relacional, será criado o tipo de entidade chamado _CollectionMeta_ que representará metadados da coleção que serão necessários para a coleta e sincronização dos dados. Estes dados são: **nome do coleção**, **nome slug**, **resource uri**, **is_member** (informa se a coleção é membro do catálogo). 

Utilizando do modelo relacional, será criado o tipo de entidade chamado _JournalMeta_ que representará metadados do periódico que serão necessários para a coleta e sincronização dos dados. Estes dados são: **nome do periódico**, **resource uri**, **is_member**. Este tipo de entidade se relaciona em N-1 com _CollectionMeta_ .

As regras para sincronização são:
- **Existe uma entidade _CollectionMeta_ cujo valor de _is_member_ é True, e que nenhuma de suas entidades _JournalMeta_ relacionadas possuem o valor de _is_member_ igual a True.** Todos os periódicos de uma coleção devem ser sincronizados.
- **Existe uma entidade _CollectionMeta_ cujo valor de _is_member_ é True, e que uma ou mais entidades _JournalMeta_ relacionadas possuem o valor de _is_member_ igual a True.** Apenas estas instâncias de _JournalMeta_ devem ser sincronizadas.

**Comment by fabiobatalha** [comment]
de acordo

**Comment by gustavofonseca** [comment]
Implementado no pull request #76
