### ISSUE TITLE
Trocar botão next da barra de navegação do periódico para ahead.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/journals-opac#58]
Implementar na classe Navigation a capacidade de identificar a url de um ahead caso ele exista no periódico.

**Comment by gustavofonseca** [comment]
Não entendi. Os botões _next_ e _ahead_ possuem funções diferentes, certo? Se sim, como podemos substituir um pelo outro?

Outra coisa, uma vez que o ahead não possui ordem na grade (ele é um balaio de artigos desassociado da grade), ele deveria ter um botão fixo na barra de navegação, certo?

**Comment by fabiobatalha** [comment]
Pois é, acho que então devemos apenas colocar um botão fixo de ahead caso exista.

**Comment by fabiobatalha** [comment]
Atualmente como manutenção do legado estamos adotando 2 campos no models.Journal.

```
    journal_data = {
                        u'current_ahead_documents': 10,
                        u'previous_ahead_documents': 10,
                    }
```

Vou desconsiderar o previous_ahead_documents, uma vez que esse não deverá existir mais no momento da implantação do novo site.

O current_ahead_documents no momento contém o número de artigos existentes em ahead, entretanto, provavelmente em um futuro próximo esse campo será ajustado para apenas um contain_ahead: boolean.

Neste caso, para esta implementação vou considerar o valor de current_ahead_documents > 0  para identificar se o periódico tem ou não artigos de ahead.

A url para apresentação de ahead terá a seguinte forma:

/ahead/[acronimo do periódico]/

Essa implementação estará no utils.Navigation
