### ISSUE TITLE
Issue().journal realiza query que poderia ser evitada

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/journals-opac#61]
Discutir sobre a possibilidade de utilizar somente um query para o mongoDB, considerando que o modelo de dados contém todos os dados necessários.

Exemplo:

view.py

```
issue = mongomodels.Issue.get_issue(journal_id, issue_id)
    journal = issue.journal
    sections = issue.list_sections()
```

mongomodels.py

```
@property
def journal(self):
"""
This method retrieves the journal related to issue instance.
"""
journal = Journal.get_journal(journal_id=self._data['acronym'])
return journal
```

**Comment by gustavofonseca** [comment]
Penso que o título deste ticket não reflete a atividade ou bug. Deveria ser algo tipo: "Issue().journal realiza query que poderia ser evitada"

**Comment by jamilatta** [comment]
Concordo, pensei na view quando escrevi o título.

**Comment by jamilatta** [comment]
Esse ticket é invalido, levando em consideração que realizamos uma alteração na projeção das queries dos métodos: get_issue() e get_section().

Verifique:

``` python
issue = cls.objects.find_one({'acronym': journal_id},
       {'issues': {'$elemMatch': {'id': int(issue_id)}}})['issues'][0]['data']
```

Se decidimos utilizar a mesma pesquisa para evitar uma nova query no banco de dados, deveriamos retornar sempre todo o registro journal.

**Comment by fabiobatalha** [comment]
Jamill, acho que não foi compreendido o funcionamento real do $elemMatch. Não houve mudança no retorno da pesquisa. A mesma continua retornando metadados de Journal + Issues.

A única coisa que mudou é que o elemMatch retorna apenas uma ocorrência de ISSUE no atributo ISSUES de Journal.

Em todo o caso eu acho que essa refatoração segue sendo desnecessária por outros motivos, como por exemplo o custo dessa query, que só é executada se chamada o metrodo issue.journal.

**Comment by jamilatta** [comment]
Descrição do operador de projeção na documentação do MongoDB:

The $elemMatch projection operator limits the contents of an array field that is included in **the query results to contain only the array element that matches the $elemMatch condition**[1].

[1]http://docs.mongodb.org/manual/reference/projection/elemMatch/

Prova de conceito:

``` python
>>> db.journals.find_one({'id': 31}, {'issues': {'$elemMatch': {'id': 1990}}})
{u'_id': ObjectId('51100441cdda6f2e349f3902'), u'issues': [{u'data': {u'is_marked_up': True, u'updated': u'2013-01-21T12:22:11.995610', u'resource_uri': u'/api/v1/issues/1990/', u'is_press_release': False, u'cover': None, u'created': u'2012-09-01T01:01:01', u'order': 9, u'ctrl_vocabulary': u'decs', u'suppl_number': None, u'number': u'9', u'publication_end_month': 9, u'label': u'90 (9)', u'volume': u'90', u'publication_year': 2012, u'total_documents': 17, u'suppl_volume': None, u'editorial_standard': u'other', u'sections': [{u'id': 889}, {u'id': 899}, {u'id': 903}, {u'id': 904}, {u'id': 905}, {u'id': 912}, {u'id': 918}, {u'id': 931}, {u'id': 933}], u'id': 1990, u'is_trashed': False, u'publication_start_month': 9}, u'id': 1990}]}
```

Comandos executados na base de dados do SciELO Saúde Pública.
