### ISSUE TITLE
Template tag list_articles_by_section está apresentando issues de forma errada no template

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/journals-opac#64]
Ao ajustar o bug #50, identifiquei que o template tag list_articles_by_section está apresentando as seções e seus respectivos artigos de forma errada no template.

**Comment by gustavofonseca** [comment]
Qual a forma errada e qual a certa?

**Comment by jamilatta** [comment]
**Erro no fechamento de algumas tags, repare**: 

<div>
</i> WHO Publications</dt><dd><ul class="unstyled toc_article"><li>Management of health-care waste in Izmir, Turkey<ul class="inline toc_article_authors"><li><a href="#">Soysal, Ahmet</a>;</li><li><a href="#">Simsek, Hatice</a>;</li><li><a href="#">Soysal, Dilek</a>;</li><li><a href="#">Alyu, Funda</a>;</li></ul><ul class="inline toc_article_links"><li>abstract: <a href="#">en</a>  | <a href="#">it</a> <dd><ul class="unstyled toc_article"><li>Management of health-care waste in Izmir, Turkey<ul class="inline toc_article_authors"><li><a href="#">Soysal, Ahmet</a>;</li><li><a href="#">Simsek, Hatice</a>;</li><li><a href="#">Soysal, Dilek</a>;</li><li><a href="#">Alyu, Funda</a>;</li></ul><ul class="inline toc_article_links"><li>abstract: <a href="#">en</a>  | <a href="#">it</a>
</div>

**forma correta**:

<div>
</i> WHO Publications</dt><dd><ul class="unstyled toc_article"><li>Management of health-care waste in Izmir, Turkey<ul class="inline toc_article_authors"><li><a href="#">Soysal, Ahmet</a>;</li><li><a href="#">Simsek, Hatice</a>;</li><li><a href="#">Soysal, Dilek</a>;</li><li><a href="#">Alyu, Funda</a>;</li></ul><ul class="inline toc_article_links"><li>abstract: <a href="#">en</a>  | <a href="#">it</a> </li></ul></li></ul></dd><dd><ul class="unstyled toc_article"><li>Management of health-care waste in Izmir, Turkey<ul class="inline toc_article_authors"><li><a href="#">Soysal, Ahmet</a>;</li><li><a href="#">Simsek, Hatice</a>;</li><li><a href="#">Soysal, Dilek</a>;</li><li><a href="#">Alyu, Funda</a>;</li></ul><ul class="inline toc_article_links"><li>abstract: <a href="#">en</a>  | <a href="#">it</a>
</div>
