### ISSUE TITLE
Implantar registros de acessos ao Ratchet

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/journals-opac#84]

**Comment by fabiobatalha** [comment]
Acho que deveríamos incluir chamadas para o ratchet nas views. 

Temos que garantir que o ratchet funcione sem handshake para não prender as views nas requisições ao ratchet.

**Comment by jamilatta** [comment]
Ver: https://github.com/thornomad/django-hitcount

Não é o nosso caso sometne para ajudar na implementação.

**Comment by fabiobatalha** [comment]
Como você havia comentado Jamil, realmente, não podemos colocar no Django uma vez que muitas das camadas pré apresentação da pagina serão cacheadas anulando o registro de log de acessos.

Como o Gustavo comentou, seria melhor aplicar a chamada para o Ratchet da mesma maneira que outros sistemas fazem, utilizando ajax.

**Comment by fabiobatalha** [comment]
Dando uma lida em alguns sites podemos notar que já existem robots mais espertos que conseguem executar javascripts e ler cookies (http://www.yottaa.com/blog/bid/223629/Google-Analytics-How-to-Segment-and-Filter-Robot-Traffic) esse é um exemplo, a fonte pode não ser conhecida, entretanto serve de insumo para pesquisarmos mais sobre o assunto e não acreditar que apenas por estar em AJAX os robots já seriam filtrados.

Uma outra forma de filtrar robots é aprimorando o arquivo robots.txt que é basicamente uma convenção para impedir que robots não façam crawler em um site, entretanto por se tratar de uma convenção (boa prática), muitos crawlers podem simplesmente ignorar a existência dos robots por interesses próprios.

Uma saída que acredito possa ser testada é criar um filtro dentro do proprio AJAX que verifica se existem padrões de string de robots dentro do user-agent para condicionar o registro de acesso ao Ratchet.

Lista de robots do projeto counter: http://www.projectcounter.org/r4/COUNTER_robot_txt_list_Jan_2011.txt

**Comment by fabiobatalha** [comment]
Para os testes utilizaremos uma lista de robots genérica:
['bot', 'link', 'web', 'lib', 'yahoo']

**Comment by fabiobatalha** [comment]
Senhores, até o momento, as definições acima foram implementadas de forma satisfatória.

Precisamos definir uma boa maneira de indicar a localidade do acesso, talvés utilizando a indicação do browser, para isso podemos utilizar a API do JQuery.
