### ISSUE TITLE
Implementação dos principais objetos de domínio

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/journals-opac#9]
Depende de [ #7 ]

Sabemos que os principais são Journal, Issue e Article. Devemos projetar suas interfaces e estratégias de colaboração.

**Comment by jamilatta** [comment]
Desenvolvido e arquitetado as relações entre as entidades, lembrando que foi criado também uma entidade que representa a Section.

Implementado métodos para listar e resgatar objetos da estrutura de dados definido.

**Comment by jamilatta** [comment]
Implementar um método na entidade Issue que permita que sejam listadas as Seções e seus correspondentes artigos.

**Comment by gustavofonseca** [comment]
Ok, mas onde está o código?

**Comment by jamilatta** [comment]
Estou implementando calma lá!!!

**Comment by jamilatta** [comment]
Pessoal entrei em loop sobre essa tarefa e gostaria de compartilhar com vocês:

Reparem que o modelo proposto do [Journal](http://docs.scielo.org/projects/journals-opac/en/latest/dev/datamodel.html#journal) contém a seções tanto no Issue quanto no Journal, porém as seções do issue tem a lista com os ids dos artigos e a seção no Journal não contém a lista de artigos entre outras diferenças.

Até aqui perfeito, mas reparem que temos uma classe que representa a [Seção](https://github.com/scieloorg/journals-opac/blob/master/opac/catalog/mongomodels.py#L175) mais externa (Journal), decição atual. Na classe Issue desenvolvemos um método que retorna as seções mais externa, porém poderia ter sido a seções mais interna, aqui nasce a questão, qual seção devemos representar na classe Section? ou as duas?

Independente da decisão de representar nessa classe Section a seção mais interna ou a seção mais externa ou as duas, já que podemos considerar que uma apenas não tem alguns atributos da outra...?, qual é a melhor forma de recuperar os artigos se caso a classe mais externa for representada, como esta hoje [desenvolvido](https://github.com/jamilatta/journals-opac/pull/new/master#L0L165)?

Esta lançada a discução, espero contar com vocês...

**Comment by gustavofonseca** [comment]
1. Instâncias de **Section** são mapeadas para o ítem **sections** no _top-level_ do registro de um **Journal**, ou a _seção mais externa_ como vc diz. Blz?
2. O ítem _journal.issues.data.sections_, ou o _mais interno_, só serve para relacionar instâncias de **Section**, **Issue** e **Article**.

Então, de acordo com os ítens acima as implementações seriam:
1. Sou uma instância de **Journal** e quero iterar em minhas seções:
   - Iterar sobre _journal.sections_
2. Sou uma instância de **Issue** e quero iterar em minhas seções:
   - Fazer uma query pelo **Journal** associado à instância do **Issue** em questão;
   - Iterar sobre _journal.issues.data.sections_, e para cada **id** de Issue, instanciar uma **Section** com os dados referentes a esta seção(por isso o passo anterior). Podemos aproveitar este momento para informar quais objetos **Article** estão vinculados à instância sendo construída.

**Comment by jamilatta** [comment]
Ajustado o método list_sections para retornar seções contendo a lista dos artigos vinculados, ver: [code](https://github.com/scieloorg/journals-opac/pull/23/files#L1L165).

Outras atividade realizadas:
1. Adicionado a estrutura do artigo ver: [code](https://github.com/scieloorg/journals-opac/pull/23/files#L2L-1)
2. Criado o método list_authors no Article;
3. Criado o método get_title na Section

Considerar o branch tk9 para avaliação dessa atividade.
